FROM node:18-alpine

WORKDIR /app

COPY backend/prisma ./prisma/
COPY backend/package*.json ./

RUN npm install

RUN npx prisma generate

COPY backend .

EXPOSE 3000

# Lệnh chạy ứng dụng
CMD ["npm", "run", "start:dev"]
