services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: frontend
    ports:
      - "8080:8080"
    depends_on:
      - backend
    environment:
      - API_URL=http://backend:3000
    networks:
      - app-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: backend
    volumes:
      - /backend/public:/app/backend/public
    ports:
      - "3000:3000"
      - "5555:5555"
    depends_on:
      - db
    environment:
      - PORT=3000
      - DATABASE_URL=mysql://root:dung2306@mysql:3306/my_db
      - DATABASE_USER=root
      - DATABASE_PASSWORD=dung2306
      - DATABASE_NAME=my_db
    env_file:
      - ./backend/.env
    networks:
      - app-network

  db:
    image: mysql:8.0
    container_name: mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: dung2306
      MYSQL_DATABASE: my_db
    env_file:
      - ./backend/.env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
